In [123]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

import numpy as np
import pandas as pd

from pathlib import Path

In [124]:
DATA_DIR = Path("../data/raw")
FILE_PATH = DATA_DIR / "fraudTest.csv"

dtf = pd.read_csv(FILE_PATH,index_col=0)

### features retained from EDA (distance_km to be computed) ###

In [126]:
numeric_features = [
    "amt",
    "city_pop",
    "lat",
    "long",
    "merch_lat",
    "merch_long",
    "distance_km",
]

categorical_features = [
    "category",
    "merchant",
    "gender",
    "state",
    "job",
]

features = numeric_features + categorical_features
target = "is_fraud"

In [127]:
# Aversine formula

lat1 = np.radians(dtf["lat"])
lon1 = np.radians(dtf["long"])

lat2 = np.radians(dtf["merch_lat"])
lon2 = np.radians(dtf["merch_long"])

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    np.sin(dlat / 2) ** 2
    + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
)

distance_km = 2 * 6371 * np.arcsin(np.sqrt(a))
dtf["distance_km"] = distance_km

### Prepare dataset split according to date of transaction (trans_date_trans_time) ###

**test dataset records after train dataset records**

In [128]:
dtf["trans_date_trans_time"] = pd.to_datetime(
    dtf["trans_date_trans_time"]
)

dtf = dtf.sort_values("trans_date_trans_time")

In [129]:
dtf["trans_date_trans_time"].min(), dtf["trans_date_trans_time"].max()

(Timestamp('2020-06-21 12:14:25'), Timestamp('2020-12-31 23:59:34'))

In [130]:
n = len(dtf)

train_end = int(n * 0.7)
val_end = int(n * 0.85)

train = dtf.iloc[:train_end].copy()
val = dtf.iloc[train_end:val_end].copy()
test = dtf.iloc[val_end:].copy()

### check ###

In [131]:
train["trans_date_trans_time"].max() < test["trans_date_trans_time"].min()

True

In [132]:
print(type(dtf.columns))
print(dtf.columns.values)
features = list(dtf.columns.values)
print(features)

<class 'pandas.Index'>
<ArrowStringArray>
['trans_date_trans_time',                'cc_num',              'merchant',
              'category',                   'amt',                 'first',
                  'last',                'gender',                'street',
                  'city',                 'state',                   'zip',
                   'lat',                  'long',              'city_pop',
                   'job',                   'dob',             'trans_num',
             'unix_time',             'merch_lat',            'merch_long',
              'is_fraud',           'distance_km']
Length: 23, dtype: str
['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud', 'distance_km']

In [133]:
X_train = train[features]
y_train = train[target]

X_val = val[features]
y_val = val[target]

X_test = test[features]
y_test = test[target]

In [134]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numeric_features,
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features,
        ),
    ]
)

logistic_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        (
            "classifier",
            LogisticRegression(
                class_weight="balanced",
                max_iter=1000,
                random_state=42,
            ),
        ),
    ]
)

### fit ###

same as 	
X_train_transformed = preprocessor.fit_transform(X_train)

	classifier.fit(
		X_train_transformed,
		y_train
	)

In [42]:
logistic_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['amt', 'city_pop', 'lat',
                                                   'long', 'merch_lat',
                                                   'merch_long',
                                                   'distance_km']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['category', 'merchant',
                                                   'gender', 'state',
                                                   'job'])])),
                ('classifier',
                 LogisticRegression(class_weight='balanced', max_iter=1000,
                                    random_state=42))])

### validation ###

In [43]:
y_val_proba = logistic_model.predict_proba(X_val)[:, 1]

In [47]:
y_val_pred = (y_val_proba >= 0.5).astype(int)

In [46]:
print(type(y_val_proba))
print(y_val_proba[:2])

<class 'numpy.ndarray'>
[1.62291556e-05 1.29083013e-01]

In [48]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)

precision = precision_score(y_val, y_val_pred)
recall = recall_score(y_val, y_val_pred)
f1 = f1_score(y_val, y_val_pred)

print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-score  : {f1:.4f}")

print(confusion_matrix(y_val, y_val_pred))

Precision : 0.0133
Recall    : 0.3534
F1-score  : 0.0255
[[75629  7446]
 [  183   100]]

### Explore diffferent thresholds ###

In [49]:
thresholds = np.arange(0.05, 0.96, 0.05)

results = []

for threshold in thresholds:
    y_pred = (y_val_proba >= threshold).astype(int)

    results.append({
        "threshold": threshold,
        "precision": precision_score(y_val, y_pred, zero_division=0),
        "recall": recall_score(y_val, y_pred, zero_division=0),
        "f1": f1_score(y_val, y_pred, zero_division=0),
    })

threshold_results = pd.DataFrame(results)

threshold_results

    threshold  precision    recall        f1
0        0.05   0.008677  0.568905  0.017094
1        0.10   0.009052  0.512367  0.017790
2        0.15   0.009293  0.473498  0.018228
3        0.20   0.009608  0.445230  0.018810
4        0.25   0.010036  0.427562  0.019613
5        0.30   0.010698  0.416961  0.020861
6        0.35   0.011289  0.402827  0.021963
7        0.40   0.012036  0.392226  0.023356
8        0.45   0.012375  0.367491  0.023944
9        0.50   0.013252  0.353357  0.025546
10       0.55   0.014763  0.349823  0.028330
11       0.60   0.015174  0.321555  0.028981
12       0.65   0.016708  0.307420  0.031694
13       0.70   0.017647  0.275618  0.033170
14       0.75   0.020235  0.261484  0.037563
15       0.80   0.023482  0.247350  0.042892
16       0.85   0.027915  0.219081  0.049521
17       0.90   0.038488  0.197880  0.064442
18       0.95   0.058424  0.151943  0.084396

In [50]:
import plotly.express as px

fig = px.line(
    threshold_results,
    x="threshold",
    y=["precision", "recall", "f1"],
    markers=True,
)

fig.show()

In [52]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(
    y_val,
    y_val_proba
)

fig = px.line(
    x=recall,
    y=precision,
    markers=True,
    labels={
        "x": "Recall",
        "y": "Precision"
    },
    title="Precision-Recall Curve"
)

fig.show()

In [53]:
idx = np.argmax(precision[:-1])

print("Precision :", precision[idx])
print("Recall    :", recall[idx])
print("Threshold :", thresholds[idx])

Precision : 0.11297071129707113
Recall    : 0.09540636042402827
Threshold : 0.9918910581676305

**On voit que le modèle Linear Regression donne une séparation limitée entre les deux classes. Le Recall est faible avec le seuil qui maximise la préçision**

### Modèle de type Random Forest Classifier ###

In [135]:
preprocessor_rf = ColumnTransformer(
    transformers=[
        (
            "num",
            "passthrough",
            numeric_features,
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features,
        ),
    ]
)

In [136]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

rf_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor_rf),
        (
            "classifier",
            RandomForestClassifier(
                class_weight="balanced",
                n_estimators=300,
                random_state=42,
                n_jobs=-1,
            ),
        ),
    ]
)

In [137]:
rf_model.fit(X_train, y_train)

y_val_proba_rf = rf_model.predict_proba(X_val)[:, 1]

In [138]:
y_val_pred_rf = (y_val_proba_rf >= 0.5).astype(int)

In [139]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)

precision = precision_score(y_val, y_val_pred_rf)
recall = recall_score(y_val, y_val_pred_rf)
f1 = f1_score(y_val, y_val_pred_rf)

print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1-score  : {f1:.4f}")

print(confusion_matrix(y_val, y_val_pred_rf))

Precision : 0.7655
Recall    : 0.3922
F1-score  : 0.5187
[[83041    34]
 [  172   111]]

**Sur l'ensemble de validation et avec un seuil de 0,5, le Random Forest obtient une Precision et un F1 nettement supérieurs à ceux de la Logistic Regression, tout en améliorant légèrement le Recall. La réduction des faux positifs est très importante**

In [140]:
thresholds = np.arange(0.05, 0.96, 0.05)

results = []

for threshold in thresholds:
    y_pred = (y_val_proba_rf >= threshold).astype(int)

    results.append({
        "threshold": threshold,
        "precision": precision_score(y_val, y_pred, zero_division=0),
        "recall": recall_score(y_val, y_pred, zero_division=0),
        "f1": f1_score(y_val, y_pred, zero_division=0),
    })

threshold_results = pd.DataFrame(results)

threshold_results

    threshold  precision    recall        f1
0        0.05   0.136465  0.862191  0.235635
1        0.10   0.266979  0.805654  0.401055
2        0.15   0.392793  0.770318  0.520286
3        0.20   0.462791  0.703180  0.558205
4        0.25   0.550296  0.657244  0.599034
5        0.30   0.617021  0.614841  0.615929
6        0.35   0.646091  0.554770  0.596958
7        0.40   0.696078  0.501767  0.583162
8        0.45   0.732143  0.434629  0.545455
9        0.50   0.765517  0.392226  0.518692
10       0.55   0.763780  0.342756  0.473171
11       0.60   0.813953  0.247350  0.379404
12       0.65   0.812500  0.183746  0.299712
13       0.70   0.875000  0.148410  0.253776
14       0.75   0.925926  0.088339  0.161290
15       0.80   0.875000  0.049470  0.093645
16       0.85   1.000000  0.017668  0.034722
17       0.90   0.000000  0.000000  0.000000
18       0.95   0.000000  0.000000  0.000000

In [141]:
from sklearn.metrics import precision_recall_curve

precision, recall, thresholds = precision_recall_curve(
    y_val,
    y_val_proba_rf
)

fig = px.line(
    x=recall,
    y=precision,
    markers=True,
    labels={
        "x": "Recall",
        "y": "Precision"
    },
    title="Precision-Recall Curve"
)

fig.show()

In [142]:
idx = np.argmax(precision[:-1])

print("Precision :", precision[idx])
print("Recall    :", recall[idx])
print("Threshold :", thresholds[idx])

Precision : 1.0
Recall    : 0.0176678445229682
Threshold : 0.8566666666666667

### Feature Engineering ###

In [143]:
dtf = dtf.sort_values("trans_date_trans_time").copy()

#### We want to consider historical card transactions history before a transaction ####

##### cc_num feature 1 : count of historical transactions for a cc_num #####

In [144]:
dtf["card_transaction_count"] = (
    dtf.groupby("cc_num").cumcount()
)

##### cc_num feature 2 : count of preceding frauds #####

In [145]:
dtf["card_fraud_count"] = (
    dtf.groupby("cc_num")["is_fraud"]
    .cumsum()
    - dtf["is_fraud"]
)

##### cc_num feature 3 : historical fraud rate #####

r = (F + alpha*p0)/(N+alpha)
- F = number of preceding frauds
- N = number of preceding transactions
- p0 = global fraud rate
- alpha = prior force

In [146]:
p0 = dtf["is_fraud"].mean()
alpha = 10

dtf["card_fraud_rate"] = (
    dtf["card_fraud_count"] + alpha * p0
) / (
    dtf["card_transaction_count"] + alpha
)

Check

In [147]:
dtf[
    [
        "trans_date_trans_time",
        "cc_num",
        "is_fraud",
        "card_transaction_count",
        "card_fraud_count",
        "card_fraud_rate",
    ]
].head(20)

,trans_date_trans_time,cc_num,is_fraud,card_transaction_count,card_fraud_count,card_fraud_rate
0,2020-06-21 12:14:25,2291163933867244,0,0,0,0.00386
1,2020-06-21 12:14:33,3573030041201292,0,0,0,0.00386
2,2020-06-21 12:14:53,3598215285024754,0,0,0,0.00386
3,2020-06-21 12:15:15,3591919803438423,0,0,0,0.00386
4,2020-06-21 12:15:17,3526826139003047,0,0,0,0.00386
5,2020-06-21 12:15:37,30407675418785,0,0,0,0.00386
6,2020-06-21 12:15:44,213180742685905,0,0,0,0.00386
7,2020-06-21 12:15:50,3589289942931264,0,0,0,0.00386
8,2020-06-21 12:16:10,3596357274378601,0,0,0,0.00386
9,2020-06-21 12:16:11,3546897637165774,0,0,0,0.00386
10,2020-06-21 12:16:20,2242542703101233,0,0,0,0.00386
11,2020-06-21 12:16:47,571465035400,0,0,0,0.00386
12,2020-06-21 12:17:21,6593250708747804,0,0,0,0.00386
13,2020-06-21 12:18:27,4988304376504,0,0,0,0.00386
14,2020-06-21 12:18:37,6011504998544485,0,0,0,0.00386
15,2020-06-21 12:18:41,4570636521433188,0,0,0,0.00386
16,2020-06-21 12:18:54,4906628655840914250,0,0,0,0.00386
17,2020-06-21 12:19:50,4908846471916297,0,0,0,0.00386
18,2020-06-21 12:19:56,4861310130652566408,0,0,0,0.00386
19,2020-06-21 12:20:13,6538441737335434,0,0,0,0.00386

In [148]:
dtf.loc[
    dtf["cc_num"] == 4725837176265195730,
    [
        "trans_date_trans_time",
        "cc_num",
        "is_fraud",
        "card_transaction_count",
        "card_fraud_count",
        "card_fraud_rate",
    ]
]

,trans_date_trans_time,cc_num,is_fraud,card_transaction_count,card_fraud_count,card_fraud_rate
4562,2020-06-22 16:34:45,4725837176265195730,0,0,0,0.003860
5416,2020-06-22 20:35:51,4725837176265195730,0,1,0,0.003509
16225,2020-06-26 23:36:15,4725837176265195730,0,2,0,0.003217
21751,2020-06-28 22:22:53,4725837176265195730,0,3,0,0.002969
23113,2020-06-29 07:36:04,4725837176265195730,0,4,0,0.002757
...,...,...,...,...,...,...
550011,2020-12-30 06:30:45,4725837176265195730,0,237,16,0.064934
551161,2020-12-30 16:16:26,4725837176265195730,0,238,16,0.064672
554327,2020-12-31 16:04:19,4725837176265195730,0,239,16,0.064412
554655,2020-12-31 17:48:13,4725837176265195730,0,240,16,0.064154
554951,2020-12-31 19:27:36,4725837176265195730,0,241,16,0.063899

In [149]:
card_features = [
    "card_transaction_count",
    "card_fraud_count",
    "card_fraud_rate",
]

dtf[card_features].describe()

       card_transaction_count  card_fraud_count  card_fraud_rate
count           555719.000000     555719.000000    555719.000000
mean               390.239182          1.283053         0.003999
std                292.891642          3.548173         0.015318
min                  0.000000          0.000000         0.000026
25%                152.000000          0.000000         0.000076
50%                332.000000          0.000000         0.000150
75%                575.000000          0.000000         0.000460
max               1473.000000         19.000000         0.566896

In [150]:
dtf[
    ["cc_num", "is_fraud"] + card_features
].head(10)

,cc_num,is_fraud,card_transaction_count,card_fraud_count,card_fraud_rate
0,2291163933867244,0,0,0,0.00386
1,3573030041201292,0,0,0,0.00386
2,3598215285024754,0,0,0,0.00386
3,3591919803438423,0,0,0,0.00386
4,3526826139003047,0,0,0,0.00386
5,30407675418785,0,0,0,0.00386
6,213180742685905,0,0,0,0.00386
7,3589289942931264,0,0,0,0.00386
8,3596357274378601,0,0,0,0.00386
9,3546897637165774,0,0,0,0.00386

In [151]:
features_to_drop = [
    "is_fraud",
    "cc_num",
    "trans_num",
    "trans_date_trans_time",
]

X = dtf.drop(columns=features_to_drop)
y = dtf["is_fraud"]

In [152]:
n = len(dtf)

train_end = int(n * 0.70)
val_end = int(n * 0.85)

X_train = X.iloc[:train_end]
y_train = y.iloc[:train_end]

X_val = X.iloc[train_end:val_end]
y_val = y.iloc[train_end:val_end]

X_test = X.iloc[val_end:]
y_test = y.iloc[val_end:]

In [153]:
numeric_features = numeric_features +card_features
print('numeric features')
print(numeric_features)
print('categorical_features')
print(categorical_features)
print

numeric features
['amt', 'city_pop', 'lat', 'long', 'merch_lat', 'merch_long', 'distance_km', 'card_transaction_count', 'card_fraud_count', 'card_fraud_rate']
categorical_features
['category', 'merchant', 'gender', 'state', 'job']

In [154]:
preprocessor_rf = ColumnTransformer(
    transformers=[
        ("num", "passthrough", numeric_features),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features,
        ),
    ]
)

In [155]:
rf_model_card = Pipeline(
    steps=[
        ("preprocessor", preprocessor_rf),
        (
            "classifier",
            RandomForestClassifier(
                class_weight="balanced",
                n_estimators=300,
                random_state=42,
                n_jobs=-1,
            ),
        ),
    ]
)

In [156]:
rf_model_card.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', 'passthrough',
                                                  ['amt', 'city_pop', 'lat',
                                                   'long', 'merch_lat',
                                                   'merch_long', 'distance_km',
                                                   'card_transaction_count',
                                                   'card_fraud_count',
                                                   'card_fraud_rate']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['category', 'merchant',
                                                   'gender', 'state',
                                                   'job'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=300, n_jobs=-1,
                                        random_state=42))])

In [157]:
y_val_proba_rf_card = (
    rf_model_card.predict_proba(X_val)[:, 1]
)

In [158]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)

threshold = 0.5

y_val_pred_rf_card = (
    y_val_proba_rf_card >= threshold
).astype(int)

print("Precision :", precision_score(y_val, y_val_pred_rf_card))
print("Recall    :", recall_score(y_val, y_val_pred_rf_card))
print("F1        :", f1_score(y_val, y_val_pred_rf_card))
print()
print(confusion_matrix(y_val, y_val_pred_rf_card))

Precision : 0.95625
Recall    : 0.5406360424028268
F1        : 0.690744920993228

[[83068     7]
 [  130   153]]

Avec l'ajout des 3 features, au seuil 0.5 on a amélioré le f1-score, le nombre de TP est en hausse et le nombre de FP a été divisé par 5.
---------------------------------- métriques du précédent modèle ----------------------------------
 
Precision : 0.7655
Recall    : 0.3922
F1-score  : 0.5187
[[83041    34]
 [  172   111]]

In [160]:
thresholds_to_test = np.arange(0.05, 1.00, 0.05)

results = []

for threshold in thresholds_to_test:
    y_pred = (
        y_val_proba_rf_card >= threshold
    ).astype(int)

    tn, fp, fn, tp = confusion_matrix(
        y_val,
        y_pred
    ).ravel()

    results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_val, y_pred, zero_division=0
        ),
        "recall": recall_score(
            y_val, y_pred, zero_division=0
        ),
        "f1": f1_score(
            y_val, y_pred, zero_division=0
        ),
        "TP": tp,
        "FP": fp,
        "FN": fn,
        "TN": tn,
    })

threshold_results_card = pd.DataFrame(results)

threshold_results_card

    threshold  precision    recall        f1   TP    FP   FN     TN
0        0.05   0.050952  0.964664  0.096791  273  5085   10  77990
1        0.10   0.148770  0.939929  0.256881  266  1522   17  81553
2        0.15   0.265608  0.886926  0.408795  251   694   32  82381
3        0.20   0.387521  0.833922  0.529148  236   373   47  82702
4        0.25   0.523342  0.752650  0.617391  213   194   70  82881
5        0.30   0.668942  0.692580  0.680556  196    97   87  82978
6        0.35   0.818584  0.653710  0.726916  185    41   98  83034
7        0.40   0.857843  0.618375  0.718686  175    29  108  83046
8        0.45   0.925287  0.568905  0.704595  161    13  122  83062
9        0.50   0.956250  0.540636  0.690745  153     7  130  83068
10       0.55   0.985816  0.491166  0.655660  139     2  144  83073
11       0.60   0.991736  0.424028  0.594059  120     1  163  83074
12       0.65   0.990566  0.371025  0.539846  105     1  178  83074
13       0.70   0.988889  0.314488  0.477212   89     1  194  83074
14       0.75   1.000000  0.257951  0.410112   73     0  210  83075
15       0.80   1.000000  0.180212  0.305389   51     0  232  83075
16       0.85   1.000000  0.113074  0.203175   32     0  251  83075
17       0.90   1.000000  0.021201  0.041522    6     0  277  83075
18       0.95   0.000000  0.000000  0.000000    0     0  283  83075

On a le meilleur f1-score vers le seuil de 0.35

In [89]:

precision, recall, thresholds = precision_recall_curve(
    y_val,
    y_val_proba_rf_card
)

fig = px.line(
    x=recall,
    y=precision,
    markers=True,
    labels={
        "x": "Recall",
        "y": "Precision"
    },
    title="Precision-Recall Curve"
)

fig.show()

##### cc_num feature 4 : card_avg_amount as-of #####

In [161]:
dtf["card_amount_sum"] = (
    dtf.groupby("cc_num")["amt"].cumsum()
    - dtf["amt"]
)

In [162]:
dtf["card_avg_amount"] = (
    dtf["card_amount_sum"]
    / dtf["card_transaction_count"]
)

##### check #####

In [163]:
card = dtf["cc_num"].iloc[0]

dtf.loc[
    dtf["cc_num"] == card,
    [
        "trans_date_trans_time",
        "amt",
        "card_transaction_count",
        "card_amount_sum",
        "card_avg_amount",
    ]
].head(20)

,trans_date_trans_time,amt,card_transaction_count,card_amount_sum,card_avg_amount
0,2020-06-21 12:14:25,2.86,0,0.00,NaN
606,2020-06-21 15:39:04,17.15,1,2.86,2.860000
4324,2020-06-22 15:24:57,89.55,2,20.01,10.005000
4340,2020-06-22 15:29:43,24.67,3,109.56,36.520000
4590,2020-06-22 16:43:19,6.28,4,134.23,33.557500
5196,2020-06-22 19:32:24,5.35,5,140.51,28.102000
5979,2020-06-22 23:21:29,12.52,6,145.86,24.310000
6424,2020-06-23 02:38:21,5.82,7,158.38,22.625714
6698,2020-06-23 04:49:53,4.04,8,164.20,20.525000
7250,2020-06-23 08:57:06,67.68,9,168.24,18.693333
8533,2020-06-23 16:42:29,38.32,10,235.92,23.592000
9063,2020-06-23 19:09:08,33.04,11,274.24,24.930909
9762,2020-06-23 22:43:23,34.41,12,307.28,25.606667
10220,2020-06-24 03:41:11,74.89,13,341.69,26.283846
10681,2020-06-24 11:19:09,69.59,14,416.58,29.755714
12181,2020-06-25 04:41:11,55.45,15,486.17,32.411333
12469,2020-06-25 08:37:52,83.63,16,541.62,33.851250
13966,2020-06-26 00:41:46,2.00,17,625.25,36.779412
14387,2020-06-26 05:57:09,4.67,18,627.25,34.847222
14457,2020-06-26 06:42:11,68.00,19,631.92,33.258947

In [164]:
card_features = card_features + ["card_avg_amount"]

In [96]:
dtf["card_avg_amount"].isna().sum()

np.int64(924)

In [165]:
numeric_features = numeric_features + ["card_avg_amount"]

In [166]:
print(numeric_features)

['amt', 'city_pop', 'lat', 'long', 'merch_lat', 'merch_long', 'distance_km', 'card_transaction_count', 'card_fraud_count', 'card_fraud_rate', 'card_avg_amount']

In [167]:
# dtf a été trié selon trans_date_trans_time asc
dtf_model = dtf.copy()

In [168]:
columns_to_drop = [
    "is_fraud",              # target
    "cc_num",                # utilisé uniquement pour créer les features historiques
    "trans_num",             # identifiant
    "trans_date_trans_time", # pas disponible à l'inférence
]

In [169]:
X = dtf_model.drop(columns=columns_to_drop)
y = dtf_model["is_fraud"]

In [170]:
numeric_features

['amt',
 'city_pop',
 'lat',
 'long',
 'merch_lat',
 'merch_long',
 'distance_km',
 'card_transaction_count',
 'card_fraud_count',
 'card_fraud_rate',
 'card_avg_amount']

In [171]:
categorical_features

['category', 'merchant', 'gender', 'state', 'job']

In [172]:
features = numeric_features + categorical_features

X = dtf_model[features]
y = dtf_model["is_fraud"]

In [173]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [174]:
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
    ]
)

In [175]:
categorical_transformer = Pipeline(
    steps=[
        (
            "onehot",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

In [176]:
preprocessor_rf = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numeric_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        ),
    ]
)

In [177]:
from sklearn.ensemble import RandomForestClassifier
rf_model_card = Pipeline(
    steps=[
        ("preprocessor", preprocessor_rf),
        (
            "classifier",
            RandomForestClassifier(
                class_weight="balanced",
                n_estimators=300,
                random_state=42,
                n_jobs=-1,
            ),
        ),
    ]
)

In [178]:
n = len(dtf_model)

train_end = int(n * 0.70)
val_end = int(n * 0.85)

X_train = X.iloc[:train_end]
y_train = y.iloc[:train_end]

X_val = X.iloc[train_end:val_end]
y_val = y.iloc[train_end:val_end]

X_test = X.iloc[val_end:]
y_test = y.iloc[val_end:]

In [180]:
rf_model_card.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['amt', 'city_pop', 'lat',
                                                   'long', 'merch_lat',
                                                   'merch_long', 'distance_km',
                                                   'card_transaction_count',
                                                   'card_fraud_count',
                                                   'card_fraud_rate',
                                                   'card_avg_amount']),
                                                 ('cat',
                                                  Pipeline(steps=[('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['category', 'merchant',
                                                   'gender', 'state',
                                                   'job'])])),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=300, n_jobs=-1,
                                        random_state=42))])

In [181]:
y_val_proba_rf_card = (
    rf_model_card.predict_proba(X_val)[:, 1]
)

In [182]:
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
)

threshold = 0.5

y_val_pred_rf_card = (
    y_val_proba_rf_card >= threshold
).astype(int)

print("Precision :", precision_score(y_val, y_val_pred_rf_card))
print("Recall    :", recall_score(y_val, y_val_pred_rf_card))
print("F1        :", f1_score(y_val, y_val_pred_rf_card))
print()
print(confusion_matrix(y_val, y_val_pred_rf_card))

Precision : 0.9605263157894737
Recall    : 0.5159010600706714
F1        : 0.671264367816092

[[83069     6]
 [  137   146]]

*Par rapport au modèle précédent, au seuil par défaut de 0.5 :
- 1 FP de moins
- mais 7 TP de moins 
- recall baisse de 2.5 points
- F1 passe de 0.691 à 0.671*

---------------------------- modèle précédent (sans feature 4) au seuil 0.5 ----------------------

Precision : 0.95625
Recall    : 0.5406360424028268
F1        : 0.690744920993228

[[83068     7]
 [  130   153]]

In [183]:
thresholds_to_test = np.arange(0.05, 1.00, 0.05)

results = []

for threshold in thresholds_to_test:
    y_pred = (
        y_val_proba_rf_card >= threshold
    ).astype(int)

    tn, fp, fn, tp = confusion_matrix(
        y_val,
        y_pred
    ).ravel()

    results.append({
        "threshold": threshold,
        "precision": precision_score(
            y_val, y_pred, zero_division=0
        ),
        "recall": recall_score(
            y_val, y_pred, zero_division=0
        ),
        "f1": f1_score(
            y_val, y_pred, zero_division=0
        ),
        "TP": tp,
        "FP": fp,
        "FN": fn,
        "TN": tn,
    })

threshold_results_card = pd.DataFrame(results)

threshold_results_card

    threshold  precision    recall        f1   TP    FP   FN     TN
0        0.05   0.049578  0.954064  0.094257  270  5176   13  77899
1        0.10   0.156805  0.936396  0.268626  265  1425   18  81650
2        0.15   0.283296  0.886926  0.429427  251   635   32  82440
3        0.20   0.426259  0.837456  0.564958  237   319   46  82756
4        0.25   0.592992  0.777385  0.672783  220   151   63  82924
5        0.30   0.724382  0.724382  0.724382  205    78   78  82997
6        0.35   0.801688  0.671378  0.730769  190    47   93  83028
7        0.40   0.858586  0.600707  0.706861  170    28  113  83047
8        0.45   0.906977  0.551237  0.685714  156    16  127  83059
9        0.50   0.960526  0.515901  0.671264  146     6  137  83069
10       0.55   0.985401  0.477032  0.642857  135     2  148  83073
11       0.60   0.983607  0.424028  0.592593  120     2  163  83073
12       0.65   1.000000  0.360424  0.529870  102     0  181  83075
13       0.70   1.000000  0.318021  0.482574   90     0  193  83075
14       0.75   1.000000  0.233216  0.378223   66     0  217  83075
15       0.80   1.000000  0.176678  0.300300   50     0  233  83075
16       0.85   1.000000  0.130742  0.231250   37     0  246  83075
17       0.90   1.000000  0.031802  0.061644    9     0  274  83075
18       0.95   0.000000  0.000000  0.000000    0     0  283  83075

|                      | Ancien RF + 3 features carte | Nouveau RF + `card_avg_amount` |
| -------------------- | ---------------------------: | -----------------------------: |
| **F1 @ 0.50**        |                       69.07% |                         67.13% |
| **F1 @ 0.40**        |                       71.87% |                         70.69% |
| **F1 @ 0.35**        |                       72.69% |                     **73.08%** |
| **Precision @ 0.35** |                       81.86% |                         80.17% |
| **Recall @ 0.35**    |                       65.37% |                     **67.14%** |

On garde le dernier modèle. L'exploration des seuils montre un F1-score max de 73.08% obtenu pour un seuil autour de 0.35 contre 72.69% pour le modèle précédent.
Pour la suite on considère qu'une décision business est de retenir un seuil autour de 0.35-0.40.

In [185]:
for name, y in [
    ("Train", y_train),
    ("Validation", y_val),
    ("Test", y_test),
]:
    print(f"{name}: {y.mean():.3%}")

Train: 0.457%
Validation: 0.339%
Test: 0.103%

**On peut voir ci-dessus que la proportion de fraudes dans l'échantillon varie notablement entre les 3 sous-ensembles et donc au cours du temps. On reviendra sur ce point après le modèle RFC avec une 4éme feature calculée. Possible dérive du dataset, possible baisse des performances**

## drift check ###

In [193]:
dtf_drift_analysis = dtf_model.copy()
dtf_drift_analysis.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'distance_km', 'card_transaction_count',
       'card_fraud_count', 'card_fraud_rate', 'card_amount_sum',
       'card_avg_amount'],
      dtype='str')

#### Evolution du taux de fraude en fonction du mois et du dataset ####

In [194]:

dtf_drift_analysis = dtf_drift_analysis.sort_values("trans_date_trans_time").reset_index(drop=True)

# splits
n = len(dtf_drift_analysis)

train_end = int(n * 0.70)
val_end = int(n * 0.85)

dtf_drift_analysis["split"] = "test"
dtf_drift_analysis.loc[:train_end - 1, "split"] = "train"
dtf_drift_analysis.loc[train_end:val_end - 1, "split"] = "validation"

# taux de fraude mensuel

dtf_drift_analysis["year"] = dtf_drift_analysis["trans_date_trans_time"].dt.year
dtf_drift_analysis["month"] = dtf_drift_analysis["trans_date_trans_time"].dt.month
dtf_drift_analysis["year_month"] = (
    dtf_drift_analysis["trans_date_trans_time"]
    .dt.to_period("M")
    .dt.to_timestamp()
)

monthly_fraud = (
    dtf_drift_analysis.groupby("year_month")
    .agg(
        fraud_rate=("is_fraud", "mean"),
        transaction_count=("is_fraud", "count"),
    )
    .reset_index()
)

train_end_date = dtf_drift_analysis.loc[train_end, "trans_date_trans_time"]
val_end_date = dtf_drift_analysis.loc[val_end, "trans_date_trans_time"]

In [195]:
split_sizes = (
    dtf_drift_analysis["split"]
    .value_counts()
    .reindex(["train", "validation", "test"])
)

split_summary = (
    dtf_drift_analysis.groupby("split")
    .agg(
        transaction_count=("is_fraud", "size"),
        fraud_count=("is_fraud", "sum"),
        fraud_rate=("is_fraud", "mean"),
        start_date=("trans_date_trans_time", "min"),
        end_date=("trans_date_trans_time", "max"),
    )
    .reindex(["train", "validation", "test"])
)

print(split_summary)

            transaction_count  fraud_count  fraud_rate          start_date  \
split
train                  389003         1776    0.004566 2020-06-21 12:14:25
validation              83358          283    0.003395 2020-11-20 18:26:42
test                    83358           86    0.001032 2020-12-13 20:01:56

                      end_date
split
train      2020-11-20 18:25:35
validation 2020-12-13 20:01:30
test       2020-12-31 23:59:34

In [196]:
import pandas as pd
import plotly.express as px

fig = px.line(
    monthly_fraud,
    x="year_month",
    y="fraud_rate",
    markers=True,
    title="Évolution du taux de fraude — Train / Validation / Test",
    labels={
        "year_month": "Mois",
        "fraud_rate": "Taux de fraude",
    },
)

fig.update_yaxes(tickformat=".2%")


# Frontière train / validation
fig.add_vline(
    x=train_end_date,
    line_dash="dash",
    annotation_text="Train → Validation",
    annotation_position="top",
)


# Frontière validation / test
fig.add_vline(
    x=val_end_date,
    line_dash="dash",
    annotation_text="Validation → Test",
    annotation_position="top",
)

fig.show()

In [197]:
fraud_by_month_split = (
    dtf_drift_analysis.groupby(["year_month", "split"])["is_fraud"]
    .agg(
        transaction_count="count",
        fraud_count="sum",
        fraud_rate="mean",
    )
    .reset_index()
)

print(fraud_by_month_split)

  year_month       split  transaction_count  fraud_count  fraud_rate
0 2020-06-01       train              30058          133    0.004425
1 2020-07-01       train              85848          321    0.003739
2 2020-08-01       train              88759          415    0.004676
3 2020-09-01       train              69533          340    0.004890
4 2020-10-01       train              69348          384    0.005537
5 2020-11-01       train              45457          183    0.004026
6 2020-11-01  validation              27178          111    0.004084
7 2020-12-01        test              83358           86    0.001032
8 2020-12-01  validation              56180          172    0.003062

In [199]:
monthly_fraud

  year_month  fraud_rate  transaction_count
0 2020-06-01    0.004425              30058
1 2020-07-01    0.003739              85848
2 2020-08-01    0.004676              88759
3 2020-09-01    0.004890              69533
4 2020-10-01    0.005537              69348
5 2020-11-01    0.004048              72635
6 2020-12-01    0.001849             139538

**On constate une baisse du taux de fraude marquée en décembre et aussi un nombre de transactions plus élevé en décembre

la frontière du split validation -> test a lieu en décembre (le 13) et le taux de fraude varie fortement engtre validation et test**

In [202]:
print(type(y_val.to_numpy()))

y_val_proba_rf_card = (
    rf_model_card.predict_proba(X_val)[:, 1]
)

print(type(y_val_proba_rf_card))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [204]:
y_val_proba_rf_card = (
    rf_model_card.predict_proba(X_val)[:, 1]
)

y_test_proba_rf_card =(
    rf_model_card.predict_proba(X_test)[:, 1]
)

THRESHOLD = 0.35


y_val_pred = (
        y_val_proba_rf_card >= THRESHOLD
).astype(int)

y_test_pred = (
    y_test_proba_rf_card >= THRESHOLD
)

def compute_metrics(split_type:str,y_pred: np.ndarray, y:np.ndarray,threshold:float, result:list):
    tn, fp, fn, tp = confusion_matrix(
            y,
            y_pred
        ).ravel()

    results.append({
        "set":split_type,
        "threshold": threshold,
        "precision": precision_score(
            y, y_pred, zero_division=0
        ),
        "recall": recall_score(
            y, y_pred, zero_division=0
        ),
        "f1": f1_score(
            y, y_pred, zero_division=0
        ),
        "TP": tp,
        "FP": fp,
        "FN": fn,
        "TN": tn,
    })

results = []
compute_metrics("val",y_val_pred,y_val.to_numpy(),THRESHOLD, results)
compute_metrics("test",y_test_pred,y_test.to_numpy(),THRESHOLD, results)

val_test_metrics = pd.DataFrame(results)

val_test_metrics

    set  threshold  precision    recall        f1   TP  FP  FN     TN
0   val       0.35    0.79668  0.678445  0.732824  192  49  91  83026
1  test       0.35    0.52500  0.732558  0.611650   63  57  23  83215

**la prévalence du taux de fraude chute fortement + la precision chute fortement + le recall reste élevé.
La baisse de prévalence pourrait expliquer une partie de la baisse de precision**

#### Vérification de l'évolution des features ####

In [205]:
comparison = (
    dtf_drift_analysis.groupby("split")
    .agg(
        avg_amt=("amt", "mean"),
        median_amt=("amt", "median"),
        avg_distance=("distance_km", "mean"),
        avg_card_transactions=("card_transaction_count", "mean"),
        avg_card_fraud_rate=("card_fraud_rate", "mean"),
    )
    .reindex(["train", "validation", "test"])
)

print(comparison)

              avg_amt  median_amt  avg_distance  avg_card_transactions  \
split
train       69.524650      47.330     76.110918             272.871425
validation  69.102917      47.530     75.995777             604.657237
test        69.067454      46.945     76.185953             723.535917

            avg_card_fraud_rate
split
train                  0.004012
validation             0.004113
test                   0.003822

#### Nombre de transactions, de fraudes et taux de fraude par catégorie d'achat pour chaque split ####

In [208]:
category_split = (
    dtf_drift_analysis.groupby(["split", "category"])["is_fraud"]
    .agg(
        transaction_count="count",
        fraud_count="sum",
        fraud_rate="mean",
    )
    .reset_index()
)

category_split.sort_values(by=["category", "fraud_count"], ascending=[True,True])

         split        category  transaction_count  fraud_count  fraud_rate
0         test   entertainment               6000            0    0.000000
28  validation   entertainment               6033            7    0.001160
14       train   entertainment              28071           52    0.001852
1         test     food_dining               5743            1    0.000174
29  validation     food_dining               5797            5    0.000863
15       train     food_dining              27728           48    0.001731
2         test   gas_transport               8417            9    0.001069
30  validation   gas_transport               8640           23    0.002662
16       train   gas_transport              39313          122    0.003103
3         test     grocery_net               2945            1    0.000340
31  validation     grocery_net               2961            6    0.002026
17       train     grocery_net              13520           34    0.002515
4         test     grocery_pos               7684           14    0.001822
32  validation     grocery_pos               7997           64    0.008003
18       train     grocery_pos              36872          407    0.011038
5         test  health_fitness               5533            1    0.000181
33  validation  health_fitness               5514            5    0.000907
19       train  health_fitness              25627           46    0.001795
6         test            home               8000            5    0.000625
34  validation            home               7767           12    0.001545
20       train            home              36578           50    0.001367
7         test       kids_pets               7340            3    0.000409
35  validation       kids_pets               7210            7    0.000971
21       train       kids_pets              34142           55    0.001611
8         test        misc_net               4035           13    0.003222
36  validation        misc_net               4108           33    0.008033
22       train        misc_net              19224          221    0.011496
9         test        misc_pos               5238            0    0.000000
37  validation        misc_pos               5130            8    0.001559
23       train        misc_pos              24206           64    0.002644
10        test   personal_care               5995            2    0.000334
38  validation   personal_care               5866            5    0.000852
24       train   personal_care              27466           63    0.002294
11        test    shopping_net               6211           25    0.004025
39  validation    shopping_net               6286           66    0.010500
25       train    shopping_net              29282          415    0.014173
12        test    shopping_pos               7634           11    0.001441
40  validation    shopping_pos               7463           39    0.005226
26       train    shopping_pos              34694          163    0.004698
13        test          travel               2583            1    0.000387
41  validation          travel               2586            3    0.001160
27       train          travel              12280           36    0.002932

**On observe que le nombre de fraudes diminue dans presque toutes les catégories entre train, val, test**

#### Répartition du nombre de transactions par catégorie pour chaque échantillon ####

In [210]:
category_distribution = (
    dtf_drift_analysis.groupby(["split", "category"])
    .size()
    .groupby(level=0)
    .transform(lambda x: x / x.sum())
    .rename("share")
    .reset_index()
)

category_distribution.sort_values(by=["split","share"], ascending=[True,False])

         split        category     share
2         test   gas_transport  0.100974
6         test            home  0.095972
4         test     grocery_pos  0.092181
12        test    shopping_pos  0.091581
7         test       kids_pets  0.088054
11        test    shopping_net  0.074510
0         test   entertainment  0.071979
10        test   personal_care  0.071919
1         test     food_dining  0.068896
5         test  health_fitness  0.066376
9         test        misc_pos  0.062837
8         test        misc_net  0.048406
3         test     grocery_net  0.035330
13        test          travel  0.030987
16       train   gas_transport  0.101061
18       train     grocery_pos  0.094786
20       train            home  0.094030
26       train    shopping_pos  0.089187
21       train       kids_pets  0.087768
25       train    shopping_net  0.075274
14       train   entertainment  0.072161
15       train     food_dining  0.071280
24       train   personal_care  0.070606
19       train  health_fitness  0.065879
23       train        misc_pos  0.062226
22       train        misc_net  0.049419
17       train     grocery_net  0.034756
27       train          travel  0.031568
30  validation   gas_transport  0.103649
32  validation     grocery_pos  0.095936
34  validation            home  0.093176
40  validation    shopping_pos  0.089529
35  validation       kids_pets  0.086494
39  validation    shopping_net  0.075410
28  validation   entertainment  0.072375
38  validation   personal_care  0.070371
29  validation     food_dining  0.069543
33  validation  health_fitness  0.066148
37  validation        misc_pos  0.061542
36  validation        misc_net  0.049281
31  validation     grocery_net  0.035521
41  validation          travel  0.031023

**On peut voir que la répartition du nombre de transactions par category évolue peut selon l'échantillon**

In [211]:
fraud_rate_by_category = (
    dtf_drift_analysis.groupby(["split", "category"])["is_fraud"]
    .mean()
    .reset_index(name="fraud_rate")
)

fraud_rate_by_category

         split        category  fraud_rate
0         test   entertainment    0.000000
1         test     food_dining    0.000174
2         test   gas_transport    0.001069
3         test     grocery_net    0.000340
4         test     grocery_pos    0.001822
5         test  health_fitness    0.000181
6         test            home    0.000625
7         test       kids_pets    0.000409
8         test        misc_net    0.003222
9         test        misc_pos    0.000000
10        test   personal_care    0.000334
11        test    shopping_net    0.004025
12        test    shopping_pos    0.001441
13        test          travel    0.000387
14       train   entertainment    0.001852
15       train     food_dining    0.001731
16       train   gas_transport    0.003103
17       train     grocery_net    0.002515
18       train     grocery_pos    0.011038
19       train  health_fitness    0.001795
20       train            home    0.001367
21       train       kids_pets    0.001611
22       train        misc_net    0.011496
23       train        misc_pos    0.002644
24       train   personal_care    0.002294
25       train    shopping_net    0.014173
26       train    shopping_pos    0.004698
27       train          travel    0.002932
28  validation   entertainment    0.001160
29  validation     food_dining    0.000863
30  validation   gas_transport    0.002662
31  validation     grocery_net    0.002026
32  validation     grocery_pos    0.008003
33  validation  health_fitness    0.000907
34  validation            home    0.001545
35  validation       kids_pets    0.000971
36  validation        misc_net    0.008033
37  validation        misc_pos    0.001559
38  validation   personal_care    0.000852
39  validation    shopping_net    0.010500
40  validation    shopping_pos    0.005226
41  validation          travel    0.001160

#### Relation montant -> fraude selon l'échantillon ####

In [213]:
amount_bins = [0, 10, 25, 50, 100, 250, 500, 1000, float("inf")]

dtf_drift_analysis["amt_bin"] = pd.cut(
    dtf_drift_analysis["amt"],
    bins=amount_bins,
    right=False
)

fraud_rate_by_amount = (
    dtf_drift_analysis.groupby(
        ["split", "amt_bin"],
        observed=True
    )["is_fraud"]
    .mean()
    .reset_index(name="fraud_rate")
)

fraud_rate_by_amount

         split          amt_bin  fraud_rate
0         test      [0.0, 10.0)    0.000323
1         test     [10.0, 25.0)    0.001202
2         test     [25.0, 50.0)    0.000000
3         test    [50.0, 100.0)    0.000000
4         test   [100.0, 250.0)    0.000397
5         test   [250.0, 500.0)    0.010807
6         test  [500.0, 1000.0)    0.067524
7         test    [1000.0, inf)    0.034483
8        train      [0.0, 10.0)    0.001189
9        train     [10.0, 25.0)    0.006683
10       train     [25.0, 50.0)    0.000238
11       train    [50.0, 100.0)    0.000154
12       train   [100.0, 250.0)    0.001096
13       train   [250.0, 500.0)    0.069672
14       train  [500.0, 1000.0)    0.190209
15       train    [1000.0, inf)    0.203671
16  validation      [0.0, 10.0)    0.000929
17  validation     [10.0, 25.0)    0.003988
18  validation     [25.0, 50.0)    0.000075
19  validation    [50.0, 100.0)    0.000000
20  validation   [100.0, 250.0)    0.001028
21  validation   [250.0, 500.0)    0.051064
22  validation  [500.0, 1000.0)    0.162162
23  validation    [1000.0, inf)    0.152542

**plus le montant est élevé, plus le taux de fraude est élevé dans tous les splits, mais la relation s'affaiblit fortement dans le temps**

En résumé

- distribution de category env stable
- distribution de amt env stable
- distribution de distance_km env stable
- Le taux de fraude baisse fortement
- même conditionnellement au montant le taux de fraude diminue
- ce qui laisse penser P(Y|X) change et pas seulement P(X)

In [214]:
# Probabilités prédites
val_proba = rf_model_card.predict_proba(X_val)[:, 1]
test_proba = rf_model_card.predict_proba(X_test)[:, 1]

In [215]:
for name, y_proba in [
    ("validation", val_proba),
    ("test", test_proba),
]:
    print(name)
    print("Nombre d'alertes :", (y_proba >= 0.35).sum())
    print("Taux d'alerte    :", (y_proba >= 0.35).mean())

validation
Nombre d'alertes : 241
Taux d'alerte    : 0.002891144221310492
test
Nombre d'alertes : 120
Taux d'alerte    : 0.0014395738861297056

In [120]:
import plotly.express as px

scores = pd.DataFrame({
    "validation": val_proba,
    "test": test_proba,
})

fig = px.histogram(
    scores,
    x=["validation", "test"],
    barmode="overlay",
    nbins=50,
    histnorm="probability",
    title="Distribution des probabilités prédites",
    labels={
        "value": "Probabilité de fraude",
        "variable": "Split",
    },
)

fig.add_vline(
    x=0.35,
    line_dash="dash",
    annotation_text="Seuil = 0.35",
)

fig.show()

In [121]:
import pandas as pd

def calibration_table(y_true, probabilities, n_bins=10):

    df = pd.DataFrame({
        "y_true": y_true,
        "probability": probabilities,
    })

    df["bin"] = pd.qcut(
        df["probability"],
        q=n_bins,
        duplicates="drop",
    )

    calibration = (
        df.groupby("bin", observed=True)
        .agg(
            mean_predicted_probability=("probability", "mean"),
            actual_fraud_rate=("y_true", "mean"),
            transaction_count=("y_true", "size"),
        )
        .reset_index()
    )

    return calibration

In [122]:
val_calibration = calibration_table(
    y_val,
    val_proba,
)

test_calibration = calibration_table(
    y_test,
    test_proba,
)

print("Validation")
print(val_calibration)

print("\nTest")
print(test_calibration)

Validation
                 bin  mean_predicted_probability  actual_fraud_rate  \
0  (-0.001, 0.00333]                    0.000335           0.000047
1    (0.00333, 0.01]                    0.007997           0.000000
2     (0.01, 0.0333]                    0.021983           0.000818
3    (0.0333, 0.937]                    0.090696           0.033919

   transaction_count
0              63544
1               4400
2               7336
3               8078

Test
                 bin  mean_predicted_probability  actual_fraud_rate  \
0  (-0.001, 0.00333]                    0.000408           0.000019
1  (0.00333, 0.0167]                    0.011081           0.000000
2   (0.0167, 0.0333]                    0.026405           0.000240
3   (0.0333, 0.0533]                    0.044681           0.000000
4    (0.0533, 0.917]                    0.095551           0.010053

   transaction_count
0              52309
1               7204
2               8330
3               7259
4               8256